simulation:
  timestep: 0.02 yr
gravity:
  softening_length: 0.3 au
  opening_angle: "0.5"
tree:
  max_depth: 20
  min_depth: 4
  max_num_particles_per_leaf: 1
visualization:
  show_quadtree: false
  camera_zoom: 1 au
output:
  output_dir: "output"
  time_between_snapshots: 0.1 yr
  fields:
    - position
    - velocity
    - mass
    - time
example:
  num_particles: 5000
  box_size: (1000 1000) au
  particle_mass: 0.2 Msol
  angular_velocity_factor: 5e-10 s^-1
