timestep:
  max_timestep: 0.2 yr
gravity:
  softening_length: 0.3 au
  opening_angle: 0.2
example:
  num_particles: 1000
  density: 1e-5 Msol au^-3
  angular_velocity_factor: 0.0 s^-1
box_size: 1000 au
visualization:
  show_particles: True
  show_quadtree: True
