timestep:
  max_timestep: 0.02 yr
gravity:
  softening_length: 0.3 au
  opening_angle: 0.5
example:
  num_particles: 1000
  density: 1e-6 Msol au^-3
  angular_velocity_factor: 5e-10 s^-1
box_size: 1000 au
visualization:
  show_particles: True
