default_job = "check"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false
watch = ["tests", "examples", "benches"]

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.test-all]
command = ["cargo", "hack", "test", "--each-feature", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.test]
command = ["cargo", "test", "--color", "always", "--tests"]
need_stdout = true
watch = ["tests", "benches", "examples"]

[jobs.test-local]
command = ["cargo", "test", "--no-default-features", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.test-2d]
command = ["cargo", "test", "--no-default-features", "--features", "mpi,2d", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.mpi-test]
command = ["cargo", "mpirun", "--np", "2", "--example", "mpi_test", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.mpi-run]
command = ["cargo", "mpirun", "--np", "2", "--example", "gravity_collapse", "--color", "always"]
need_stdout = true
watch = ["tests", "examples", "benches"]

[jobs.docs]
command = ["cargo", "doc", "--color", "always"]
need_stdout = true

[keybindings]
2 = "job:test-2d"
a = "job:test-all"
i = "job:initial"
c = "job:clippy-all"
b = "job:check-all"
d = "job:docs"
t = "job:test"
r = "job:mpi-run"
k = "job:kill"
l = "job:test-local"
m = "job:mpi-test"