[package]
name = "raxiom"
version = "0.1.0"
edition = "2021"
resolver="2"
authors = [
    "Toni Peter <mail@tonipeter.de>",
]

[features]
default = ["mpi"]
mpi = []
mpi_test = []

[dependencies]
bevy = { version = "0.8.0", default-features = false, features = ["render", "x11", "bevy_winit"]}
bevy_prototype_lyon = "0.6.0"
clap = {version = "3.2.17", features = ["derive"]}
derive_more = "0.99.17"
glam = "0.21.3"
hdf5 = "0.8.1"
lazy_static = "1.4.0"
mpi = { version = "0.6", default-features = false, features = ["derive"] }
ndarray = "0.15.6"
serde = {version = "1.0.143", features = ["derive"] }
serde_yaml = "0.9.9"
derive_named = { path = "derive_named" }
diman = { path = "diman", features = ["mpi", "hdf5", "serde"] }
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

# Optimize dependencies even in a debug build
[profile.dev.package."*"]
opt-level = 3

[[example]]
name = "mpi_test"
required-features = ["mpi", "mpi_test"]

[[example]]
name = "figure8"
required-features = ["mpi"]

[[example]]
name = "viscous_hydro"
required-features = ["mpi"]

[[example]]
name = "fake_periodic_boundary_conditions"
required-features = ["mpi"]

[[example]]
name = "gravity_collapse"
required-features = ["mpi"]

[[bench]]
name = "hydrodynamics"
harness = false
