[package]
name = "tenet"
version = "0.1.0"
edition = "2021"
resolver="2"

[features]
local = []

[dependencies]
bevy = { version = "0.8.0", default-features = false, features = ["render", "x11", "bevy_winit", "serialize", "filesystem_watcher"]}
bevy_prototype_lyon = "0.6.0"
clap = {version = "3.2.17", features = ["derive"]}
glam = "0.21.3"
lazy_static = "1.4.0"

# Use the system feature which uses the system library.
# This is because the autoconfigure/build script of libffi (the C project, not the crate) seems to be bugged on my machine
# since it is trying to invoke cc -V which my gcc doesnt support (and hasnt since 2013?)
libffi = { version = "3.0.0", features = ["system"] }
mpi = { version = "0.6", features = ["user-operations", "derive"] }
once_cell = "1.13.0"
rand = "0.8.5"
serde = {version = "1.0.143", features = ["derive"] }
serde_yaml = "0.9.9"

# Optimize dependencies even in a debug build
[profile.dev.package."*"]
opt-level = 3
