physics:
  timestep: 1e-2 s
visualization:
  show_quadtree: false
  camera_zoom: 2e-3 m
output:
  output_dir: "output"
  time_between_snapshots: 0.1 yr
  fields:
    - position
    - velocity
    - mass
    - time
