physics:
  timestep: 15e2 s
domain_tree:
  max_depth: 20
  min_depth: 4
  max_num_particles_per_leaf: 1
visualization:
  show_quadtree: false
  camera_zoom: 8e7 m
output:
  output_dir: "output"
  time_between_snapshots: 0.1 yr
  fields:
    - position
    - velocity
    - mass
    - time
viscous_gravity:
  num_particles: 1000
  fake_gravity_factor: 3e-9 s^-2
  fake_viscosity_timescale: 3e4 s
