timestep:
  max_timestep: 1e-2 s
gravity:
  softening_length: 1e-10 m
  opening_angle: 0.5
input:
  paths:
    - examples/figure8/ics.hdf5
box_size:
  min: (-2 -2) m
  max: (2 2) m
visualization:
  show_particles: True
