[package]
name = "derive_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.143", features = ["derive"] }
bevy = { version = "0.9.0", default-features = false, features = []}