timestep:
  max_timestep: 1e-3 s
hydrodynamics:
  min_smoothing_length: 0.5 m
  initial_gas_energy:
    temperature: 100 K
    molecular_weight: 4 dimensionless
domain:
  tree:
    max_depth: 20
    min_depth: 4
    max_num_particles_per_leaf: 1
example:
  num_particles: 3000
  box_size: (45 8) m
  top_fluid:
    density: 0.05 kg m^-2
    initial_velocity: 100 m s^-1
  bottom_fluid:
    density: 0.15 kg m^-2
    initial_velocity: -100 m s^-1
visualization:
  show_particles: True
