timestep:
  max_timestep: 1e-4 s
hydrodynamics:
  min_smoothing_length: 0.5 m
  initial_gas_energy:
    temperature: 300 K
    molecular_weight: 4 dimensionless
domain:
  tree:
    max_depth: 20
    min_depth: 4
    max_num_particles_per_leaf: 1
example:
  num_particles: 3000
  top_fluid:
    density: 0.05 kg m^-2
    initial_velocity: 0 m s^-1
  bottom_fluid:
    density: 0.05 kg m^-2
    initial_velocity: 0 m s^-1
box_size: (8 8) m
visualization:
  show_particles: True
  color_map:
    type: Pressure
    scale: 1e5 N m^-1
