physics:
  softening_length: 1 au
  opening_angle: "0.5"
  timestep: 0.001 yr
tree:
  max_depth: 20
  min_depth: 4
  max_num_particles_per_leaf: 1
visualization:
  show_quadtree: false
initial_conditions:
  num_particles: 10000
  type: Normal
output:
  output_dir: "output"
  time_between_snapshots: 0.1 yr
  fields:
    - position
    - velocity
    - time
