physics:
  softening_length: 1e-3 m
  opening_angle: "0.5"
tree:
  max_depth: 20
visualization:
  show_quadtree: false
initial_conditions:
  num_particles: 100
output:
  output_dir: "output"
  time_between_snapshots: 1.0 s
  time_first_snapshot: 1.0 s
