physics:
  softening_length: 1 au
  opening_angle: "0.5"
  timestep: 0.001 yr
tree:
  max_depth: 20
  min_depth: 3
  max_num_particles_per_leaf: 1
visualization:
  show_quadtree: true
initial_conditions:
  num_particles: 100
  type: Normal
output:
  output_dir: "output"
  time_between_snapshots: 1.0 s
  time_first_snapshot: 1.0 s
  fields:
    - position
    - velocity
    - time
