name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Install hdf5 libraries
        run: |
          sudo apt-get update
          sudo apt-get install libhdf5-dev
      - name: Install mpich libraries
        run: |
          sudo apt-get update
          sudo apt-get install mpich
      - name: Build
        run: cargo build --verbose --all-targets
      - name: Run tests
        run: cargo test --tests
      - name: Run local communication tests
        run: cargo test --no-default-features --tests -- --ignored
      - name: Run 2d tests
        run: cargo test --no-default-features --features mpi,2d --tests -- --ignored
      - name: Build benchmarks
        run: cargo bench --no-run
      - name: Run clippy on all targets
        run: cargo clippy --all-targets -- -D warnings
      - name: Doctests
        run: cargo test --doc
