name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install hdf5 libraries
        run: |
          sudo apt-get update
          sudo apt-get install libhdf5 libhdf5-dev
      - name: Build
        run: cargo build --verbose --all-targets
      - name: Run tests
        run: cargo test --verbose
      - name: Run local communication tests
        run: cargo test --verbose --no-default-features
